// Generated by CoffeeScript 1.6.2
(function() {
  var AppRouter, routeToArticle;

  AppRouter = Backbone.Router.extend({
    routes: {
      '': 'home',
      'index.html': 'home',
      ':level': 'blockGrid',
      'post/:file_name': 'post'
    },
    home: function() {
      return null;
    },
    post: function(file_name) {
      return routeToArticle(file_name);
    },
    blockGrid: function(level) {
      return routeToArticle(level);
    }
  });

  $(document).ready(function() {
    var appRouter;

    appRouter = new AppRouter();
    return Backbone.history.start();
  });

  routeToArticle = function(level) {
    var fileInfo, id;

    id = isFinite(level) ? level : articleView.getFileId(level);
    fileInfo = articleView.getFileUrls();
    return articleView.render(id, fileInfo);
  };

}).call(this);
